### ISSUE TITLE
POST /bounded/collection should accept 303 ?

### ISSUE THREAD

**Issue by jeanparpaillon** [CESNET/pOCCI#3]
Test OCCI/CORE/CREATE/001 fails with erocci because it returns 303 with the location of the created entity.

Given that the operation is done on an url (collection) and results in the creation of a new entity, I suppose 303 should be an authorized status code ?

**Comment by jeanparpaillon** [comment]
Following tests have the same issue:
OCCI/INFRA/CREATE/001
OCCI/INFRA/CREATE/002
OCCI/INFRA/CREATE/003

**Comment by jeanparpaillon** [comment]
When server returns 303 (See Other), test should get the location of created entity from 'location' header

**Comment by valtri** [comment]
Actually the current standard OCCI 1.1 permits only the HTTP 200 and 201 (although this also needs to be fixed in pOCCI).

See https://www.ogf.org/documents/GFD.185.pdf:

"The OCCI implementation MAY either return 201 or 200 HTTP return
codes. If the OCCI implementation returns the 200 HTTP response code
the full representation (as described in ’Retrieving a resource
instance’ in this section) MUST be returned. Please note that the HTTP
Location header used when the service returns the 201 HTTP response
code is defined in RFC2616 [5]. A created resource instance MUST be
added to the collection defined by the Kind."

**Comment by jeanparpaillon** [comment]
Ok, 201 seems more appropriate
(btw, let's forget the pr, I will propose another one accepting 201)
